### ISSUE TITLE
What is the significance of this state input?

### ISSUE THREAD

**Issue by 851682852** [godka/Ruyi#1]
https://github.com/godka/Ruyi/blob/2336d87148502573ed43e26fd5889245756bdbf4/src/test_ruyi.py#L133

**Comment by godka** [comment]
Hi there,

I got your question. Just for changes in QoE parameters – sorry, I cannot answer questions related to this project due to insufficient documentation. If you are interested, you can contact the author of Ruyi, who is also one of the project's maintainers.

Best,
Tianchi
